#ifndef AUTOGEN_FILE_STRINGS_H_INCLUDED
#define AUTOGEN_FILE_STRINGS_H_INCLUDED

typedef enum {
    STRINGS_SCELTA_PROGRAMMA = 0,
    STRINGS_MACCHINA_AL_LAVORO,
    STRINGS_MACCHINA_IN_PAUSA,
    STRINGS_PROGRAMMA_CALDO,
    STRINGS_PROGRAMMA_MEDIO,
    STRINGS_PROGRAMMA_TIEPIDO,
    STRINGS_PROGRAMMA_FREDDO,
    STRINGS_PROGRAMMA_LANA,
    STRINGS_ALLARME_OBLO_APERTO,
    STRINGS_ALLARME_EMERGENZA,
    STRINGS_ALLARME_TEMPO_SCADUTO_T1,
    STRINGS_ALLARME_ERRORE_RAM,
    STRINGS_ALLARME_INVERTER,
    STRINGS_ALLARME_FILTRO_APERTO,
    STRINGS_ALLARME_BLOCCO_BRUCIATORE,
    STRINGS_ALLARME_TEMPERATURA_1,
    STRINGS_ALLARME_FLUSSO_ARIA,
    STRINGS_AVVISO_ANTIPIEGA,
    STRINGS_AVVISO_DRY_CONTROL,
    STRINGS_AVVISO_SOVRATEMPERATURA,
    STRINGS_ALLARME_ANOMALIA_ARIA,
    STRINGS_AVVISO_MANUTENZIONE,
    STRINGS_ITALIANO,
    STRINGS_INGLESE,
    STRINGS_CONTRASTO_LCD,
    STRINGS_STATISTICHE,
    STRINGS_TEMPO_ACCENSIONE,
    STRINGS_TEMPO_LAVORO,
    STRINGS_TEMPO_MOTO,
    STRINGS_TEMPO_VENTILAZIONE,
    STRINGS_TEMPO_RISCALDAMENTO,
    STRINGS_CICLI_PARZIALI,
    STRINGS_CICLI_TOTALI,
    STRINGS_GETTONI_TOTALI,
    STRINGS_ERRORE_FATALE_RAM,
    STRINGS_ERRORE_LIEVE_RAM,
} strings_t;

extern const char *strings[36][2];

#endif
