#ifndef AUTOGEN_FILE_STRINGS_H_INCLUDED
#define AUTOGEN_FILE_STRINGS_H_INCLUDED

typedef enum {
    STRINGS_SCELTA_PROGRAMMA = 0,
    STRINGS_PROGRAMMA_CALDO,
    STRINGS_PROGRAMMA_MEDIO,
    STRINGS_PROGRAMMA_TIEPIDO,
    STRINGS_PROGRAMMA_FREDDO,
    STRINGS_PROGRAMMA_LANA,
} strings_t;

extern const char *strings[6][2];

#endif
