const char *strings[50][5] = {
    {"Inserire moneta", "Insert coin", "inserer une piece", "Münze einwerfen", "Wloz monete", },
    {"Inserire gettone", "Insert token", "inserer jeton", "Token einfugen", "Wloz zeton", },
    {"Pagare cassa", "Pay at desk", "payer au caissier", "bezahlen Kasse", "Zaplac przy kasie", },
    {"Scelta programma", "Choose program", "choix programme", "Programmwahl", "Wybierz program", },
    {"al  lavoro", "at work", "au travail", "auf Arbeit", "W czasie pracy", },
    {"pausa lavoro", "pause", "pause", "pause", "Pauza", },
    {"CALDO", "HOT", "CHAUD", "HEISSE", "GORACY", },
    {"MEDIO", "WARM", "MEDIUM", "MITTEL", "CIEPLY", },
    {"TIEPIDO", "TEPID", "PEU CHAUD", "WENIG HEISS", "POSREDNI", },
    {"FREDDO", "COLD", "FROID", "KALT", "ZIMNY", },
    {"LANA", "WHOOL", "LAINE", "WOLLE", "WELNA", },
    {"E MEMORIA", "E MEMORY", "E MEMOIRE", "E ERINNERUNG", "E PAMIEC", },
    {"PORTA APERTA", "OPEN DOOR", "PORTE OUVERTE", "OFFENE TÜR", "DRZWI OTWARTE", },
    {"OBLO' SBLOCCATO", "OBLO' SBLOCCATO", "OBLO' SBLOCCATO", "OBLO' SBLOCCATO", "DRZWI ODBLOKOWANE", },
    {"EMERGENZA", "EMERGENCY", "URGENCE", "NOTFALL", "NAGLY WYPADEK", },
    {"NO RISCALDAMENTO", "NO HEATING", "PAS DE CHAUFFAGE", "KEINE HEIZUNG", "BRAK GRZANIA", },
    {"NO INVERTER", "NO INVERTER", "ONDULEUR", "NO INVERTER", "BRAK FALOWNIKA", },
    {"FILTRO  APERTO", "OPEN FILTER", "FILTRE OUVERT", "FILTER OFFNEN", "OTWARTY FILTR", },
    {"E BRUCIATORE", "E BURNER", "E BRULEUR", "E BRENNER", "E PALNIK", },
    {"E TEMPERATURA", "E TEMPERATURE", "E TEMPERATURE", "E TEMPERATUR", "E TEMPERATURA", },
    {"NO  ARIA", "NO AIR", "PAS D'AIR", "KEINE LUFT", "BRAK POWIETRZA", },
    {"ANOMALIA  ARIA", "AIR PRESSURE", "PRESSION DE L'AIR", "LUFTDRUCK", "CISNIENIE POWIETRZA", },
    {"ANTIPIEGA", "WRINKLE FREE", "ANTIFROISSEMENT", "KNITTSCHUTZ", "BEZ ZMARSZCZEK", },
    {"APRIRE OBLO'", "APRIRE OBLO'", "APRIRE OBLO'", "APRIRE OBLO'", "DRZWI OTWARTE", },
    {"DRY  CONTROL", "DRY  CONTROL", "DRY  CONTROL", "DRY  CONTROL", "DRY  CONTROL", },
    {"TEMPERATURA ALTA", "OVER TEMPERATURE", "SURCHAUFFE", "UBERTEMPERATUR", "ZA WYSOKA TEMP.", },
    {"MANUTENZIONE", "MAINTENANCE", "ENTRETIEN", "WARTUNG", "KONSERWACJA", },
    {"AVV PW OFF !", "AVV PW OFF !", "AVV PW OFF !", "AVV PW OFF !", "AVV PW OFF!", },
    {"ITALIANO", "ITALIAN", "ITALIEN", "ITALIENISCH", "WLOSKI", },
    {"INGLESE", "ENGLISH", "ANGLAIS", "ZAPISYWANIE", "ANGIELSKI", },
    {"FRANCESE", "FRENCH", "FRANCAIS", "FRANZOSISCH", "FRANCUSKI", },
    {"TEDESCO", "GERMAN", "ALLEMAND", "DEUTSCH", "NIEMIECKI", },
    {"POLACCO", "POLISH", "POLONAIS", "POLIEREN", "POLSKI", },
    {"CONTRASTO LCD", "LCD CONTRAST", "LCD CONTRAST", "LCD CONTRAST", "KONTRAST LCD", },
    {"STATISTICHE", "STATISTICS", "STATISTIQUES", "STATISTIKEN", "STATYSTYKI", },
    {"Tempo attivo", "Active time", "Temps actif", "Aktive Zeit", "AKTYWNY CZAS", },
    {"Tempo lavoro", "Work time", "Temps de travail", "Arbeitszeit", "CZAS PRACY", },
    {"Tempo azione", "Action time", "Temps d'action", "Aktionszeit", "CZAS AKTYWNOSCI", },
    {"Tempo ventilaz", "Fan time", "Temps ventilat", "Lüftungszeit", "CZAS WENTYLACJI", },
    {"Tempo riscald.", "Heating time", "Temps chauffe", "Erhitzungszeit", "CZAS NAGRZEWANIA", },
    {"Cicli parziali", "Partial cycles", "cycles partiels", "Teilzyklen", "CZĘSCIOWE CYKLE", },
    {"Cicli totali", "Total cycles", "cycles totaux", "Gesamtzyklen", "CYKLE W SUMIE", },
    {"Totale gettoni", "Total coins", "jetons totaux", "Gesamttoken", "MONETY W SUMIE", },
    {"Si e' verificato un malfunzionamento fatale della eeprom. I parametri non verranno caricati", "Si e' verificato un malfunzionamento fatale della eeprom. I parametri non verranno caricati", "Si e' verificato un malfunzionamento fatale della eeprom. I parametri non verranno caricati", "Si e' verificato un malfunzionamento fatale della eeprom. I parametri non verranno caricati", "Si e' verificato un malfunzionamento fatale della eeprom. I parametri non verranno caricati", },
    {"I parametri caricati dalla eeprom non erano validi. Sono stati corretti", "I parametri caricati dalla eeprom non erano validi. Sono stati corretti", "I parametri caricati dalla eeprom non erano validi. Sono stati corretti", "I parametri caricati dalla eeprom non erano validi. Sono stati corretti", "I parametri caricati dalla eeprom non erano validi. Sono stati corretti", },
    {"Salvataggio in corso...", "Saving...", "Saving .... ", "Saving....", "ZAPISYWANIE", },
    {"TEMPO CICLO", "CYCLE TIME", "TEMPS DE CYCLE", "ZYKLUSZEIT", "CZAS CYKLU", },
    {"TEMPERATURA", "TEMPERATURE", "TEMPÉRATURE", "TEMPERATURE", "TEMPERATURA", },
    {"UMIDITA' ", "UMIDITY", "UMIDITY", "UMIDITY", "WILGOTNOSC", },
    {"VELOCITA'", "SPEED", "VITESSE", "DREHZAHL", "PREDKOSC", },
};

